# Generated by Django 2.2.5 on 2019-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_date',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
